name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Build React app
      run: npm run build

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Azure Container Registry
      run: echo ${{ secrets.ACR_PASSWORD }} | docker login appregistry.azurecr.io -u appregistryv2 --password-stdin

    - name: Build and push Docker image
      run: |
        docker build -t appregistryv2.azurecr.io/appv2:${{ github.sha }} .
        docker push appregistryv2.azurecr.io/appv2:${{ github.sha }}

    - name: Set up Azure CLI
      uses: azure/cli@v1
      with:
        azcliversion: 2.0.72

    - name: Log in to Azure
      run: az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

    - name: Get AKS credentials
      run: az aks get-credentials --resource-group appgroup --name aksapp

    - name: Deploy to AKS using Ansible
      uses: robertdebock/ansible-playbook-action@v1.0.1
      with:
        playbook: ansible/deploy_to_aks.yml
